FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

WORKDIR /app-root/

# Install dependencies, including runtime libraries
RUN microdnf install --setopt=tsflags=nodocs -y python3.11 python3.11-pip python3.11-devel which gcc gcc-c++ make zlib zlib-devel openssl-libs openssl-devel libzstd libzstd-devel zip && \
    microdnf upgrade -y && \
    microdnf clean all

RUN set -ex && if [ -e `which python3.11` ]; then ln -s `which python3.11` /usr/local/bin/python; fi

RUN python -m pip install --upgrade pip && \
    python -m pip install pipenv --ignore-installed

# pipenv install --system --ignore-pipfile
