= Ephemeral Environment.

First make sure one has the access to ephemeral cluster and has bonfire and oc binary install in the PATH. For more details regarding getting access and downloading oc and bonfire binary please go through the doc - https://consoledot.pages.redhat.com/docs/dev/getting-started/ephemeral/onboarding.html[Onboarding to the Ephemeral Cluster]

== Run Yuptoo in Ephemeral Environment.

Login to the cluster by grabbing a login command from https://oauth-openshift.apps.c-rh-c-eph.8p0c.p1.openshiftapps.com/oauth/token/request[token request page] for the ephemeral cluster
----
oc login --token=sha256~xxxxxx --server=https://api.c-rh-c-eph.8p0c.p1.openshiftapps.com:6443
----

Run bonfire command to reserve the ephemeral namespace and to deploy yuptoo in that namespace
----
bonfire deploy yuptoo
----
Above command will return the name of namespace which has been reserved, make a note of it. 

To check if all the pods are running below command can be used. 
----
oc get pods -n <reserved-namespace>
----

Below command can be used to follow the yuptoo process logs. 
----
oc logs -f yuptoo-yuptoo-service-xxxxxx -n <reserved-namespace>
----

== Upload tarball to yuptoo in Ephemeral Environment

----
make sample-data
make ephemeral-upload-data file=temp/sample_data_ready_******.tar.gz env=<reserved-namespace>
----