{
 "title": "Yuptoo",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": "yuptoo-stage, yuptoo-prod" },
   { "name": "datasources_aws", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "gauge",
   "description": "Yuptoo pod up avg_over_time",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{service=\"yuptoo-service\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Reports Downloaded",
   "type": "stat",
   "description": "Total number of reports downloaded from s3",
   "gridPos": { "h": 3, "w": 6, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(yuptoo_archive_downloaded_success_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reports Download failed",
   "type": "stat",
   "description": "Total number of reports failed downloaded from s3",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(yuptoo_archive_failed_to_download_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka failures ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(yuptoo_kafka_failures_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming hosts",
   "type": "stat",
   "description": "Total number of hosts found in reports. ",
   "gridPos": { "h": 3, "w": 6, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(yuptoo_incoming_hosts_counter_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reports processing exceptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(yuptoo_report_processing_exceptions_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Report extraction failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(yuptoo_extract_report_slices_failures_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host uploaded to HBI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(yuptoo_host_uploaded_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed to upload host to HBI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(yuptoo_host_upload_failures_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yuptoo Consumer Lag",
   "type": "timeseries",
   "description": "yuptoo consumer group lag",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_kafka_sum_offset_lag_sum{topic=\"platform.upload.announce\", consumer_group=\"qpc-group\"}",
     "legendFormat": "{{consumer_group}}"
    }
   ]
  }
 ]
}